### ISSUE TITLE
Multilingual translation with shared vocabulary, embeddings and softmax

### ISSUE THREAD

**Issue by martinpopel** [tensorflow/tensor2tensor#242]
According to #9 (and #235), I can train English-German translation jointly in both directions by following the Walkthrough instructions and just using `--problems=translate_ende_wmt32k-translate_ende_wmt32k_rev`. In addition, I have set batch_size=1024 to prevent out-of-memory errors.
This fails with
`ValueError: Variable symbol_modality_33952_512/input_emb/weights_0 does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`

Inspired by #207, I tried `--hparams='batch_size=1024,shared_embedding_and_softmax_weights=0'` and it works (and takes a lot of memory). However, in my case, the vocabulary is shared (the default `vocab.endefr`) for both problems, so I hope also the embeddings and softmax weights could be shared. Is it possible?

Other questions:
Even if I set shared_embedding_and_softmax_weights=0, I may want to share the English embeddings for both en->de and de->en problems (and similarly for the German embeddings). Is there a parameter to control this? Or is it done automatically whenever the modality ID is the same (`problem.SpaceID.EN_TOK`)?

**Comment by lukaszkaiser** [comment]
This is a bug with setting reuse in T2TModel. It could be easily corrected by setting `reuse=tf.AUTO_REUSE` in T2TModel, but AUTO_REUSE didn't make it into TF 1.4. Getting through the reuse garden manually to make it work with TF 1.3 is a little tricky (and will probably cause other bugs), so we were thinking we'll just wait for TF 1.4 and use AUTO_REUSE. You could in the meantime get a TF nightly and change all reuses in T2TModel to AUTO_REUSE. Sorry that I don't have a more satisfying answer for now, but I think going with AUTO_REUSE is the right thing to do in the long run (as in: in a few weeks, not that long hopefully).

**Comment by lukaszkaiser** [comment]
Sorry, a typo. I mean: it didn't make it into TF 1.3, but will be there in TF 1.4. We don't want to force T2T users to use nighlies, that's why we wait for stable TF to use it's new features.

**Comment by martinpopel** [comment]
Thanks for a great answer. I just wanted to know if I just did something wrong or it is easy to fix (and possibly I can contribute with a PR), or it is a known bug that is difficult to fix. Now I see it is the third case, but will become the second case, once TF 1.4 is out.
Once again: thanks for all the great work you do in Google Brain and esp. for open-sourcing it.

**Comment by martinpopel** [comment]
Update with tensorflow-gpu 1.4.0, tensor2tensor 1.2.9.:
The problem is still here, same as above, just
- the message says "tf.AUTO_REUSE" instead of "None", i.e. it says "...Did you mean to set reuse=tf.AUTO_REUSE in VarScope?"
- batch_size=1024 failed with OOM, I had to decrease it to 512 (on the same GPU as before, with 11 GB memory).

**Comment by martinpopel** [comment]
According to recent posts in #413 I guess this issue can be reclassified as a feature request as well.
It is a pity that multi-model mode was dropped in T2T, I hoped at least multi-lingual translation could be still supported.

**Comment by rsepassi** [comment]
@martinpopel We'd be happy to add support back. Just need to figure out the cleanest way to do so in the new structure. Closing here in favor of the #413 so we can discuss what may be required.
